# Generated by Django 4.1.6 on 2023-04-13 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
    ]
