# Generated by Django 4.1.6 on 2023-04-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingslot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookingslot',
            new_name='mybookingslot',
        ),
    ]
