# Generated by Django 4.1.6 on 2023-04-13 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingslot', '0002_rename_bookingslot_mybookingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybookingslot',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 13, 12, 40, 12, 282339, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
