# Generated by Django 4.1.6 on 2023-04-15 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingslot', '0003_mybookingslot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybookingslot',
            name='time',
            field=models.TextField(default=datetime.datetime(2023, 4, 15, 5, 55, 38, 522246, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
