# Generated by Django 4.1.6 on 2023-04-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingslot', '0004_mybookingslot_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybookingslot',
            name='time',
        ),
    ]
