# Generated by Django 4.1.6 on 2023-04-15 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingslot', '0005_remove_mybookingslot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybookingslot',
            name='time',
            field=models.TextField(default=datetime.datetime(2023, 4, 15, 16, 59, 3, 221714, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
