# Generated by Django 4.1.6 on 2023-04-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletpay',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='walletpay',
            name='x',
        ),
    ]
